# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Ifi131286
  demands:
  - agent.name -equals az400m05-vm0

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm audit fix
  displayName: 'npm install'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    npm run build
  displayName: 'npm build'
- script: |
    npm test
  displayName: 'npm test'
